### ISSUE TITLE
Seems to be abanoned?

### ISSUE THREAD

**Issue by Justinzobel** [abdularis/LANShare#53]
Author has lots of commits in private repos but inactive here.

I was hoping to send a PR for a Flatpak build but not sure if it'll be used. I'll stick it here anyway since I found it useful as I'm not a fan of AppImage:

```
app-id: com.github.abdularis.LAN-Share
command: LANShare
runtime: org.kde.Platform
runtime-version: '5.15-23.08'
sdk: org.kde.Sdk
finishing-args:
  - --device=dri
  - --socket=fallback-x11
  - --socket=wayland
  - --system-talk-name=org.freedesktop.UDisks2
modules:
  - name: LAN-Share
    buildsystem: simple
    build-commands:
      - qmake ./src/LANShare.pro PREFIX=/app -o Makefile
      - make
      - install -Dm755 LANShare /app/bin/LANShare
      - install -D ./packaging/linux/debian/LANShare.desktop /app/share/applications/LANShare.desktop
      - install -D ./packaging/linux/debian/lanshare-icon.png /app/share/pixmaps/lanshare-icon.png
    sources:
      - type: git
        url: https://github.com/abdularis/LAN-Share.git
        branch: master
```
